General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/config/tls/server.key
    Certificate: /var/hyperledger/config/tls/server.crt
    RootCAs:
      - /var/hyperledger/config/tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  GenesisMethod: file
  GenesisFile: /var/hyperledger/config/genesis.block
  LocalMSPDir: /var/hyperledger/config/msp
  LocalMSPID: OrdererMSP
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  Authentication:
    TimeWindow: 15m

FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: hyperledger-fabric-ordererledger

RAMLedger:
  HistorySize: 1000

Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    Consumer:
      RetryBackoff: 2s
  Verbose: false
  TLS:
    Enabled: false
    PrivateKey:
    Certificate:
    RootCAs:
  SASLPlain:
    Enabled: false
    User:
    Password:
  Topic:
    ReplicationFactor: 1

Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

Operations:
  ListenAddress: 0.0.0.0:9443
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/config/tls/server.key
    Certificate: /var/hyperledger/config/tls/server.crt
    RootCAs:
      - /var/hyperledger/config/tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:

Metrics:
  Provider: prometheus
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 10s
    Prefix: